obt_colegio:
    path:     /obt/colegio/{comuna}
    defaults: { _controller: PsumateBundle:Default:ObtenerColegio  }

obt_region:
    path:     /obt/region
    defaults: { _controller: PsumateBundle:Default:ObtenerRegion  }

obt_comuna:
    path:     /obt/comuna/{region}
    defaults: { _controller: PsumateBundle:Default:ObtenerComuna  }