obt_colegio:
    path:     /obt/colegio/{comuna}
    defaults: { _controller: PsumateBundle:Default:ObtenerColegio  }

obt_region:
    path:     /obt/region
    defaults: { _controller: PsumateBundle:Default:ObtenerRegion  }

obt_comuna:
    path:     /obt/comuna/{region}
    defaults: { _controller: PsumateBundle:Default:ObtenerComuna  }

ing_beca:
    path:     /ing/beca
    defaults: { _controller: PsumateBundle:Default:IngBeca  }

ing_info:
    path:     /ing/info
    defaults: { _controller: PsumateBundle:Default:IngInfo  }

login:
    path:     /login
    defaults: { _controller: PsumateBundle:User:login  }

register:
    path:     /register
    defaults: { _controller: PsumateBundle:User:register  }

obt_unidades:
    path:     /obt/unidades
    defaults: { _controller: PsumateBundle:Videos:ObtenerUnidades  }

obt_capitulos:
    path:     /obt/capitulos
    defaults: { _controller: PsumateBundle:Videos:ObtenerCapitulos  }

obt_todos_capitulos:
    path:     /obt/capitulos/todos
    defaults: { _controller: PsumateBundle:Videos:ObtenerTodosCapitulos  }

obt_videos:
    path:     /obt/videos
    defaults: { _controller: PsumateBundle:Videos:ObtenerVideos  }    

obt_videos_todos:
    path:     /obt/videos/todos
    defaults: { _controller: PsumateBundle:Videos:obtenerVideosTodos  }    

   
ing_unidades:
    path:     /ing/unidades
    defaults: { _controller: PsumateBundle:Videos:IngresarUnidades  }    

ing_capitulos:
    path:     /ing/capitulos
    defaults: { _controller: PsumateBundle:Videos:IngresarCapitulos  }   

ing_videos:
    path:     /ing/videos
    defaults: { _controller: PsumateBundle:Videos:IngresarVideos  }

obt_revision:
    path:   /obt/revision
    defaults:    { _controller: PsumateBundle:Revision:ObtenerRevision }

obt_lista_revision:
    path:   /obt/revision/lista/
    defaults:    { _controller: PsumateBundle:Revision:ObtenerListaRevision }

obt_detalle_revision:
    path:   /obt/revision/detalle/
    defaults:    { _controller: PsumateBundle:Revision:ObtenerDetalleRevision }

obt_adm_capitulos:
    path:     /obt/adm/capitulos
    defaults: { _controller: PsumateBundle:Videos:ObtenerAdmCapitulos  }

obt_adm_unidades:
    path:     /obt/adm/unidades
    defaults: { _controller: PsumateBundle:Videos:ObtenerAdmUnidades  }

ing_adm_unidades:
    path:     /ing/adm/unidades
    defaults: { _controller: PsumateBundle:Revision:IngresarRevisionUnidad  }

obt_adm_revision_lista:
    path:     /obt/adm/revision/listas
    defaults: { _controller: PsumateBundle:Revision:ObtenerAdmRevisionLista  }

ing_adm_revision_listas:
    path:     /ing/adm/revision/listas
    defaults: { _controller: PsumateBundle:Revision:IngresarRevisionLista  }
    
obt_adm_revision_list:
    path:     /obt/adm/revision/list
    defaults: { _controller: PsumateBundle:Revision:ObtenerAdmRevisionListas  }

ing_adm_revision:
    path:     /ing/adm/revision
    defaults: { _controller: PsumateBundle:Revision:IngresarRevision  }

ing_revision:
    path:     /ing/revision
    defaults: { _controller: PsumateBundle:Revision:IngresarRevisionAlumno  }