obt_colegio:
    path:     /obtener/colegio
    defaults: { _controller: PsumateBundle:Default:ObtenerColegio  }

obt_region:
    path:     /obtener/region
    defaults: { _controller: PsumateBundle:Default:ObtenerRegion  }

obt_comuna:
    path:     /obtener/comuna
    defaults: { _controller: PsumateBundle:Default:ObtenerComuna  }